package com.orbit.recommendation.model;

public enum RuleType {
    RESUME_INCOMPLETE,
    SEQUENTIAL_PROGRESS,
    PATH_CONTINUATION,
    INACTIVITY_NUDGE,
    CONSISTENCY_REINFORCEMENT,
    BINGE_CONTROL,
    DROPOFF_AVOIDANCE,
    PREREQUISITE_REINFORCEMENT,
    EXPLORATION_BOOST,
    SKILL_DIVERSIFICATION,
    COLD_START,
    SAFE_DEFAULT
}

